"""empty message

Revision ID: 0994d3e72692
Revises: 338163e2fec4
Create Date: 2025-05-03 13:34:28.798992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0994d3e72692'
down_revision = '338163e2fec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_csv_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_csv_entry')
    # ### end Alembic commands ###
