"""Fix friend request relationships

Revision ID: 0d9e776957e1
Revises: 6e7098777ffe
Create Date: 2025-05-06 17:38:47.762135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9e776957e1'
down_revision = '6e7098777ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('friends')
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_friend_request', ['sender_id', 'receiver_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.drop_constraint('unique_friend_request', type_='unique')

    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('friendships')
    # ### end Alembic commands ###
