"""add win flags & score (nullable)

Revision ID: 1d0ce11c1bb9
Revises: cca14122a949
Create Date: 2025-05-15 16:12:24.189797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0ce11c1bb9'
down_revision = 'cca14122a949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('went_first', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('first_time_playing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('first_time_playing')
        batch_op.drop_column('went_first')
        batch_op.drop_column('win')

    # ### end Alembic commands ###
