"""create player_game_entry table

Revision ID: cca14122a949
Revises: e34770ccca05
Create Date: 2025-05-15 15:27:15.077152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca14122a949'
down_revision = 'e34770ccca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_entry_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('win', sa.String(length=3), nullable=True),
    sa.Column('went_first', sa.String(length=3), nullable=True),
    sa.Column('first_time', sa.String(length=3), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_entry_id'], ['game_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_favorite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('entry_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['game_entry.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_post_fav_post_id_post'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('player_game_entry')
    # ### end Alembic commands ###
