"""Add gameentry_permissions table for GameEntry access control

Revision ID: e34770ccca05
Revises: e1b837d96967
Create Date: 2025-05-08 15:31:04.804978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34770ccca05'
down_revision = 'e1b837d96967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameentry_permissions',
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['game_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameentry_permissions')
    # ### end Alembic commands ###
