"""empty message

Revision ID: ec27174fae12
Revises: e34770ccca05
Create Date: 2025-05-16 15:17:00.424200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec27174fae12'
down_revision = 'e34770ccca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('went_first', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('first_time_playing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('first_time_playing')
        batch_op.drop_column('went_first')
        batch_op.drop_column('win')

    # ### end Alembic commands ###
